vendor_saved_apps := \
	AMAPNetworkLocation \
	Bluetooth \
	BluetoothExt \
	BluetoothMidiService \
	com.qualcomm.qti.services.secureui \
	datastatusnotification \
	embms \
	fastdormancy \
	miui \
	MiuiBluetooth \
	miuisystem \
	NfcNci \
	PacProcessor \
	PicoTts \
	PrintSpooler \
	QtiGbaAuthService \
	QtiTelephonyService \
	SecurityCoreAdd \
	shutdownlistener \
	Stk \
	telresources \
	TimeService \
	CNEService \
	com.qualcomm.location \
	DefaultContainerService \
	FingerprintServiceExtension \
	ims \
	MiuiCamera \
	qcrilmsgtunnel \
	QtiTetherService
